### ISSUE TITLE
get_activity_stream fails when logged in

### ISSUE THREAD

**Issue by niedakh** [KartikTalwar/Duolingo#51] opened 2017-12-26 23:36 UTC
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
~/virtualenvs/p3/lib/python3.5/site-packages/duolingo.py in get_activity_stream(self, before)
     43         try:
---> 44             return request.json()
     45         except:

~/virtualenvs/p3/lib/python3.5/site-packages/requests/models.py in json(self, **kwargs)
    891                     pass
--> 892         return complexjson.loads(self.text, **kwargs)
    893 

/usr/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:

/usr/lib/python3.5/json/decoder.py in decode(self, s, _w)
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()

/usr/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-34-70c4f0c04c1c> in <module>()
----> 1 lingo.get_activity_stream()

~/virtualenvs/p3/lib/python3.5/site-packages/duolingo.py in get_activity_stream(self, before)
     44             return request.json()
     45         except:
---> 46             raise Exception('Could not get activity stream')
     47 
     48     def _switch_language(self, lang):

Exception: Could not get activity stream
```

**Comment by funnyflowerpot** [comment] 2018-08-19 19:15
Hi. I can confirm this. Also with Python 3 and with current code from `master`, my output is like this:

```
>>> lingo.get_activity_stream()
Traceback (most recent call last):
  File "/home/XXX/.local/lib64/python3.5/site-packages/duolingo.py", line 44, in get_activity_stream
    return request.json()
  File "/usr/lib64/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.5/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXX/.local/lib64/python3.5/site-packages/duolingo.py", line 46, in get_activity_stream
    raise Exception('Could not get activity stream')
Exception: Could not get activity stream
```

**Comment by funnyflowerpot** [comment] 2018-08-19 19:17
However, I am not sure whether the error is because I am logged in or not.

**Comment by joshcoales** [comment] 2020-02-20 17:45
I think this is tested and working now, closing ticket

**Closed by joshcoales** 2020-02-20 17:45 UTC
